version: '3.8'

services:
  mongo1:
    image: mongo:5
    command: >
      bash -c "
      mongod --replSet rs0 --bind_ip_all --port 27017 &
      sleep 5 &&
      chmod +x /init-replica.sh &&
      /init-replica.sh
      "
    ports:
      - 27017:27017
    networks:
      - mongo_network
    volumes:
      - mongo1_data:/data/db
      - ./init-replica.sh:/init-replica.sh
    depends_on:
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy

  mongo2:
    image: mongo:5
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - 27018:27017
    networks:
      - mongo_network
    volumes:
      - mongo2_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo3:
    image: mongo:5
    command: mongod --replSet rs0 --bind_ip_all --port 27017
    ports:
      - 27019:27017
    networks:
      - mongo_network
    volumes:
      - mongo3_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  mongo_network:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: